"""
Sets of Gram stain positive and negative bacteria.

These genera come from:
 - https://en.wikipedia.org/w/index.php?title=Category:Gram-positive_bacteria
 - https://en.wikipedia.org/w/index.php?title=Category:Gram-negative_bacteria

Note: This list has been curated to remove non-genus entries like adjectives,
      terms, and duplicates that were incorrectly scraped from Wikipedia categories.
"""

gram_positive = {'Absicoccus', 'Acetatifactor', 'Acetivibrio', 'Acetoanaerobium', 'Actinomyces', 'Actinomycetota', 'Aerococcus', 'Alicyclobacillus', 'Anaerobutyricum', 'Anaerostipes', 'Bacillales', 'Bacillus', 'Bavariicoccus', 'Bifidobacterium', 'Blautia', 'Carnobacteriaceae', 'Catenibacterium', 'Christensenella', 'Clostridioides', 'Clostridium', 'Coriobacteriia', 'Corynebacterium', 'Cutibacterium', 'Deinococcus', 'Desulfitobacterium', 'Effusibacillus', 'Ellagibacter', 'Enterocloster', 'Enterococcus', 'Faecalicoccus', 'Fervidobacterium', 'Floccifex', 'Fodinibacter', 'Frisingicoccus', 'Fusicatenibacter', 'Granulicatella', 'Halobacillus', 'Hathewaya', 'Hornefia', 'Inconstantimicrobium', 'Intestinibaculum', 'Kribbia', 'Kyrpidia', 'Lacrimispora', 'Lacticaseibacillus', 'Lactiplantibacillus', 'Lactobacillus', 'Lactococcus', 'Latilactobacillus', 'Lawsonibacter', 'Lentilactobacillus', 'Ligilactobacillus', 'Limosilactobacillus', 'Listeriaceae', 'Macrococcus', 'Mesobacillus', 'Microbispora', 'Mobiluncus', 'Nocardia', 'Oceanobacillus', 'Oliverpabstia', 'Ornithinibacter', 'Paraclostridium', 'Paratractidigestivibacter', 'Pasteuria', 'Pauljensenia', 'Peptoniphilus', 'Peptostreptococcales', 'Pilibacter', 'Propionibacterium', 'Rhodococcus', 'Robertmurraya', 'Roseburia', 'Rossellomorea', 'Rothia', 'Ruminiclostridium', 'Sarcina', 'Schaalia', 'Sharpea', 'Solibacillus', 'Sporosarcina', 'Staphylococcus', 'Streptococcus', 'Syntrophomonas', 'Tepidibacter', 'Terrisporobacter', 'Thermoclostridium', 'Thomasclavelia', 'Trueperella', 'Tumebacillus', 'Turicibacter', 'Weissella', 'Winkia', 'Zhenhengia'}
gram_negative = {'Acinetobacter', 'Actinobacillus', 'Agrobacterium', 'Akkermansia', 'Anaerobiospirillum', 'Anaerolinea', 'Arcobacter', 'Azotobacter', 'Bacteroides', 'Bartonella', 'Bibersteinia', 'Bradyrhizobium', 'Caldilinea', 'Cardiobacterium', 'Chryseobacterium', 'Coxiella', 'Dehalogenimonas', 'Desulfurobacterium', 'Devosia', 'Dinoroseobacter', 'Dysosmobacter', 'Ekhidna', 'Enterobacter', 'Escherichia', 'Flavobacterium', 'Fusobacterium', 'Glaesserella', 'Gluconacetobacter', 'Haemophilus', 'Helicobacter', 'Kingella', 'Klebsiella', 'Kluyvera', 'Kosakonia', 'Kozakia', 'Legionella', 'Leptonema', 'Leptotrichia', 'Levilinea', 'Lonepinella', 'Luteimonas', 'Mannheimia', 'Meiothermus', 'Methylobacterium', 'Methylomirabilis', 'Mixta', 'Moraxella', 'Morganella', 'Mycoplasma', 'Neisseria', 'Nitrosomonas', 'Novosphingobium', 'Otariodibacter', 'Oxalobacter', 'Paucimonas', 'Pelistega', 'Phocaeicola', 'Pluralibacter', 'Proteus', 'Protochlamydia', 'Pseudoalteromonas', 'Pseudomonas', 'Pseudoxanthomonas', 'Pyramidobacter', 'Raineya', 'Rhizorhabdus', 'Rickettsia', 'Ruthenibacterium', 'Salinibacter', 'Salinicola', 'Salmonella', 'Serratia', 'Sodaliphilus', 'Solobacterium', 'Sorangium', 'Sphaerotilus', 'Sphingobacterium', 'Sphingomonas', 'Sphingosinicella', 'Stenotrophomonas', 'Thalassolituus', 'Thermotoga', 'Thiomargarita', 'Tomasiella', 'Trinickia', 'Veillonella', 'Vibrio', 'Victivallis'}
